#!/usr/bin/ruby

if ARGV[0] == "-h" or ARGV[0] == "--help" or ARGV.length == 0
  puts
  puts "    Usage: tweetnotify [-#] command"
  puts "           Argument is the index of the command to include in tweet."
  puts "           If none given defaults to the first argument."
  puts 
  exit
end

TWITTER_USERNAME = "kevinwuhoo"

dash = ARGV[0][0].chr
num = ARGV[0][1..-1]

if "-" == dash  and /^[\d]+([\d]+){0,1}$/ === num
  tweet_arg = Integer(num)
  cmd_start = 1
else
  tweet_arg = 0
  cmd_start = 0
end

if tweet_arg > ARGV.length - 1
  puts "Tweet script name is out of range."
  exit
end

system(ARGV[cmd_start..-1].join(" "))

tweet_program = ARGV[tweet_arg].split("/")
tweet_program = tweet_program[tweet_program.length - 1]
system("twurl -d 'status=Hey @#{TWITTER_USERNAME}, #{tweet_program} is done! Get back to work!' /1/statuses/update.xml > /dev/null")
